name: ci

on:
  pull_request:
  push:

env:
  GO_VERSION: 1.18

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: build
        run: |
          make melange
          ./melange version

      - uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # v2.8.1
        with:
          version: v1.5.0
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/melange-build_linux_amd64/melange version
