name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.18

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.46.2
      - run: |
          go mod tidy
          git diff --exit-code
